version: '3.4'

services:
  web:
    container_name: php-container
    # image: php:apache
    # restart: unless-stopped
    # command: docker-php-ext-install mysqli
    build: .
    volumes:
      - $PWD:/var/www/html
    ports:
      - 80:80
      - 443:443
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    # depends_on:
    #   - mydb
    # links:
    #   - mydb

  mydb:
    container_name: mysql-container
    image: mysql:5.7
    # restart: unless-stopped
    environment:
      # - MYSQL_DATABASE=app
      # - MYSQL_USER=app
      # - MYSQL_PASSWORD=app
      # - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=project
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "23306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: